### ISSUE TITLE
Resource links issue

### ISSUE THREAD

**Issue by vinugawade** [dishant0406/lazyweb#11]
I've created an account here with my Github account and added my 2 new resources to the site so I've added the link and fetch there info.
https://vinugawade.github.io/s-php &
https://github.com/vinugawade/ur-cache-cleaner (I was unable to fetch info of my actual extension link published on VS Code marketplace)
After adding catagory and tags I published this 2 resource on site but when I tried to access their links, I can only get this
https://vinugawade.github.io instead of https://vinugawade.github.ios-php &
https://github.com instead of https://github.com/vinugawade/ur-cache-cleaner.

Why it's happening? Please check once.

**Comment by dishant0406** [comment]
The issue has been resolved kindly check and add the resources you want to add.
