### ISSUE TITLE
Optimize Site Images for Improved Load Time and User Experience

### ISSUE THREAD

**Issue by nickmackenzie** [dishant0406/lazyweb#12]
The images on the main site are absolutely massive. The initial load of the website is nearly 20mb. Improve the UX by compressing the images or resizing them to fit the size they are presented. See "resources.png" for example.

**Comment by dishant0406** [comment]
I have improved the images on both https://lazyweb.rocks and https://app.lazyweb.rocks
The intial load of the website now is decreased from 20mb to 2mb

**Comment by nickmackenzie** [comment]
Awseome. Such a great imporovement.
