### ISSUE TITLE
Add a button to copy the link of the top product

### ISSUE THREAD

**Issue by dishant0406** [dishant0406/lazyweb#14]
On app.lazyweb.rocks there a section which shows top product of the day
![image](https://user-images.githubusercontent.com/90952604/219590897-ffde838f-522f-47f3-b81b-f5846eb9d057.png)
add a button after the link to copy the link instead of opening it so that when the user clicks on the link, he/she can copy the link automatically.

**Comment by Priyamakeshwari** [comment]
i would like to work on this issue under JWOC

**Comment by dishant0406** [comment]
okay @Priyamakeshwari I am assigning the issue to you

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @dishant0406

**Comment by dishant0406** [comment]
Hello @priyanka1551 currenlty this issue is already assigned if possible kindly pickup any other issue from the issues section

**Comment by dishant0406** [comment]
@Priyamakeshwari instead of a button like this can you use a icon from the icon pack that is used that is react-icons so that it can match the style

**Comment by Priyamakeshwari** [comment]
Ya sure, i'll update by tmrw

**Comment by dishant0406** [comment]
okay

**Comment by dishant0406** [comment]
![image](https://user-images.githubusercontent.com/90952604/219943631-01455ead-9f66-489b-92f8-77d809fe6c72.png)
Can you customize it a little more to make it look like this
![image](https://user-images.githubusercontent.com/90952604/219943647-c48e3815-3bdb-468f-8157-ac57c02724d8.png)
these are the changes

**Comment by dishant0406** [comment]
Great Work @Priyamakeshwari

**Comment by Priyamakeshwari** [comment]
Thanks 😊
