### ISSUE TITLE
Add GitHub Repository link

### ISSUE THREAD

**Issue by Coding-Hashira** [dishant0406/lazyweb#3]
As this repository is now open source, I think we should add a GitHub repository link in the main landing page so that everyone can contribute to it! I think the best for that will be footer.

Could you please assign this issue to me?

**Comment by dishant0406** [comment]
Thankyou for mentioning this @Coding-Hashira. The Landing page is on another repository.

https://github.com/dishant0406/lazyweb-landing-page

I guess first we have to make a mono repo for both of them.

**Comment by dishant0406** [comment]
@Coding-Hashira the monorepo setup is complete I am assigning the task of adding github repo link to the landing page to you

**Comment by Coding-Hashira** [comment]
That's awesome, mate! 🙌

Are you using any packages for icons? If not, can I use react-icons? 🤔

**Comment by dishant0406** [comment]
I am using react icons already
