### ISSUE TITLE
Should have more catagories & tags.

### ISSUE THREAD

**Issue by vinugawade** [dishant0406/lazyweb#9]
We should add more catagories like `Open source Tools` or `VS Code Extensions` or any tools or modules related to any perticular development tool or IDE.

Also we could add more tags, if any of tag is  not exist it should create new one so we can use it again. Tags will help us to search better and more accurate.

**Comment by dishant0406** [comment]
Hy @vinugawade, if the tag or category that you want to add is not available in the dropdown you can create one by entering the category or tag name in the input box
![image](https://user-images.githubusercontent.com/90952604/218506650-8d2e4da3-9d8e-4e58-938f-c287498b578b.png)

**Comment by vinugawade** [comment]
@dishant0406 Thanks for help! I'll do that. Closing this issue now.
